name: Deploy static content to Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check dist folder
        run: |
          echo "Checking dist folder contents:"
          ls -la dist/
          echo "Checking if index.html exists:"
          test -f dist/index.html && echo "✅ index.html found" || echo "❌ index.html not found"
          echo "Checking if openapi.yaml exists:"
          test -f dist/openapi.yaml && echo "✅ openapi.yaml found" || echo "❌ openapi.yaml not found"
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 